### ISSUE TITLE
过多的进程怎么办

### ISSUE THREAD

**Issue by rainmeterLotus** [iqiyi/Andromeda#21]
`<application>
        <activity android:name=".MedaActivity" android:process=":meda_main" />
        <activity android:name=".MedaActivity1" android:process=":meda_main1" />
        <activity android:name=".MedaActivity2" android:process=":meda_main2" />
        <activity android:name=".MedaActivity3" android:process=":meda_main3" />
        <activity android:name=".MedaActivity4" android:process=":meda_main4" />
        <activity android:name=".MedaActivity5" android:process=":meda_main5" />
        <activity android:name=".MedaActivity6" android:process=":meda_main6" />
        <activity android:name=".MedaActivity7" android:process=":meda_main7" />
        <activity android:name=".MedaActivity8" android:process=":meda_main8" />
        <activity android:name=".MedaActivity9" android:process=":meda_main9" />
        <activity android:name=".MedaActivity10" android:process=":meda_main10" />
        <activity android:name=".MedaActivity11" android:process=":meda_main11" />
        <activity android:name=".MedaActivity12" android:process=":meda_main12" />
        <activity android:name=".MedaActivity13" android:process=":meda_main13" />
        <activity android:name=".MedaActivity14" android:process=":meda_main14" />
        <activity android:name=".MedaActivity15" android:process=":meda_main15" />
        <activity android:name=".MedaActivity16" android:process=":meda_main16" />
        <activity android:name=".MedaActivity17" android:process=":meda_main17" />
        <activity android:name=".MedaActivity18" android:process=":meda_main18" />
        <activity android:name=".MedaActivity19" android:process=":meda_main19" />
        <activity android:name=".MedaActivity20" android:process=":meda_main20" />
    </application>`
error:
Cause: no such class: org.qiyi.video.svg.stub.CommuStubService$CommuStubService15

ps:一般一个应用不会出现这么多进程，只是测试了一下，出现这种情况！

**Comment by HiWong** [comment]
呃，就是考虑到一般没这么多进程，所以我觉得目前插桩的CommuStubService够用了，其实也可以编译时按需要动态生成类，但是时间原因没这么做。

**Comment by rainmeterLotus** [comment]
ok，谢谢
