### ISSUE TITLE
使用AndResGuard和Redex进行包体大小减小，会出现FileNotFoundException

### ISSUE THREAD

**Issue by cxMax** [iqiyi/Andromeda#28]
如题。
异常主要是这句话 ：
java.io.FileNotFoundException: /Users/caixi/AndroidStudioProjects/android_hox/app/build/outputs/apk/DevTest/debug/AndResGuard_app-DevTest-debug/temp/org/qiyi (Not a directory)
解压编译生成的apk。
![image](https://user-images.githubusercontent.com/17964075/49980995-d80e7600-ff90-11e8-9395-b9957ff305c6.png)
想请问下， 这两个文件夹在编译过程中，是如何加进去的呢，它的作用是什么呢？ 作者方便的话，可以解答下吗。 谢谢啦

**Comment by cxMax** [comment]
apk直接使用本项目编译的

**Comment by taaco** [comment]
> apk直接使用本项目编译的

怎样改能让不生成这个org文件呢？

**Comment by cxMax** [comment]
> > apk直接使用本项目编译的
> 
> 怎样改能让不生成这个org文件呢？

sorry， 这个编译生成org package的原理， 我也不是很清楚， 不好意思。 之前的项目没有解决掉这个问题。 不过其他项目， 没有用到这套组件化框架， 使用AndResGuard都能正常混淆压缩res文件。 

不过我想AndResGuard失效，不一定是这个org package的问题， 得看下编译时候的log
